# Generated by Django 4.2.7 on 2025-09-14 02:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('prefer_not_say', 'Prefer not to say')], max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('education_level', models.CharField(blank=True, choices=[('high_school', 'High School'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD'), ('trade', 'Trade/Vocational'), ('other', 'Other')], max_length=50)),
                ('preferred_locations', models.JSONField(default=list, help_text='List of preferred suburbs/areas')),
                ('max_commute_time', models.IntegerField(blank=True, help_text='Maximum commute time in minutes', null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)])),
                ('has_car', models.BooleanField(default=False)),
                ('min_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('preferred_room_type', models.CharField(blank=True, choices=[('private', 'Private Room'), ('shared', 'Shared Room'), ('master', 'Master Room with Ensuite'), ('studio', 'Studio/Granny Flat')], max_length=30)),
                ('lease_duration', models.CharField(blank=True, choices=[('short', 'Short-term (1-6 months)'), ('medium', 'Medium-term (6-12 months)'), ('long', 'Long-term (12+ months)'), ('flexible', 'Flexible')], max_length=20)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('cleanliness_level', models.IntegerField(default=5, help_text='1 = Very messy, 10 = Extremely clean', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('noise_tolerance', models.IntegerField(default=5, help_text="1 = Need complete quiet, 10 = Don't mind noise", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('social_level', models.IntegerField(default=5, help_text='1 = Very private, 10 = Very social', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('smoker', models.CharField(choices=[('never', 'Never'), ('occasionally', 'Occasionally'), ('regularly', 'Regularly')], default='never', max_length=20)),
                ('drinking', models.CharField(choices=[('never', 'Never'), ('socially', 'Socially'), ('regularly', 'Regularly')], default='socially', max_length=20)),
                ('pets', models.CharField(choices=[('none', 'No pets'), ('cat', 'Have cat(s)'), ('dog', 'Have dog(s)'), ('other', 'Have other pets'), ('want_pets', 'Want to get pets')], default='none', max_length=30)),
                ('schedule_type', models.CharField(blank=True, choices=[('regular', 'Regular 9-5'), ('shift', 'Shift work'), ('flexible', 'Flexible hours'), ('student', 'Student'), ('freelance', 'Freelance/Self-employed')], max_length=20)),
                ('works_from_home', models.BooleanField(default=False)),
                ('preferred_age_min', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(99)])),
                ('preferred_age_max', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(99)])),
                ('preferred_gender', models.CharField(choices=[('any', 'No preference'), ('same', 'Same gender only'), ('female_only', 'Female only'), ('male_only', 'Male only')], default='any', max_length=20)),
                ('max_roommates', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('bio', models.TextField(blank=True, help_text='Tell others about yourself', max_length=1000)),
                ('interests', models.JSONField(default=list, help_text='List of interests/hobbies')),
                ('languages', models.JSONField(default=list, help_text='Languages spoken')),
                ('phone_verified', models.BooleanField(default=False)),
                ('id_verified', models.BooleanField(default=False)),
                ('background_check', models.BooleanField(default=False)),
                ('references_provided', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/pictures/')),
                ('additional_photos', models.JSONField(default=list, help_text='List of additional photo URLs')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_views', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'profiles_userprofile',
            },
        ),
    ]
