# Generated by Django 4.2.7 on 2025-09-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('renter', 'Renter'), ('landlord', 'Landlord'), ('admin', 'Administrator')], default='renter', max_length=10),
        ),
    ]
